//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.25 at 11:35:46 AM PKT 
//


package com.aspose.componentsdownload;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aspsoe.componentsdownload package. 
 * <p>An ObjectFactoryComponents allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactoryComponents {


    /**
     * Create a new ObjectFactoryComponents that can be used to create new instances of schema derived classes for package: com.aspsoe.componentsdownload
     * 
     */
    public ObjectFactoryComponents() {
    }

    /**
     * Create an instance of {@link ProductRelease }
     * 
     */
    public ProductRelease createProductRelease() {
        return new ProductRelease();
    }

}
